import {
  VillagerBirthdayMonth,
  VillagerDebut,
  VillagerGender,
  VillagerName,
  VillagerPersonality,
  VillagerQuote,
  VillagerSign,
  VillagerSpecies,
} from "./types";

/** 주민 종족을 한글로 변환하는 함수 */
export const convertSpeciesToKorean = (species: VillagerSpecies) => {
  const speciesMap: Record<VillagerSpecies, string> = {
    Bird: "새",
    Squirrel: "다람쥐",
    Pig: "돼지",
    "Bear cub": "아기곰",
    Gorilla: "고릴라",
    Alligator: "악어",
    Koala: "코알라",
    Eagle: "독수리",
    Anteater: "개미핥기",
    Penguin: "펭귄",
    Bull: "황소",
    Mouse: "쥐",
    Cat: "고양이",
    Horse: "말",
    Hamster: "햄스터",
    Kangaroo: "캥거루",
    Wolf: "늑대",
    Chicken: "닭",
    Elephant: "코끼리",
    Rhinoceros: "코뿔소",
    Lion: "사자",
    Sheep: "양",
    Deer: "사슴",
    Tiger: "호랑이",
    Dog: "개",
    Bear: "곰",
    Cow: "소",
    Hippo: "하마",
    Duck: "오리",
    Goat: "염소",
    Ostrich: "타조",
    Rabbit: "토끼",
    Frog: "개구리",
    Octopus: "문어",
    Monkey: "원숭이",
  };

  return speciesMap[species] || species;
};

/** 주민 성격을 한글로 변환하는 함수 */
export const convertPersonalityToKorean = (
  personality: VillagerPersonality
) => {
  const personalityMap: Record<VillagerPersonality, string> = {
    Jock: "운동광",
    Cranky: "무뚝뚝한",
    Peppy: "활발한",
    "Big sister": "단순활발",
    Lazy: "먹보",
    Normal: "친절한",
    Snooty: "성숙한",
    Smug: "느끼한",
  };

  return personalityMap[personality] || personality;
};

/** 주민 성별을 한글로 변환하는 함수 */
export const convertGenderToKorean = (gender: VillagerGender) => {
  const genderMap: Record<VillagerGender, string> = {
    Male: "수컷",
    Female: "암컷",
  };

  return genderMap[gender] || gender;
};

/** 생일 월을 한글로 변환하는 함수 */
export const convertMonthToKorean = (month: VillagerBirthdayMonth) => {
  const monthMap: Record<VillagerBirthdayMonth, string> = {
    January: "1월",
    February: "2월",
    March: "3월",
    April: "4월",
    May: "5월",
    June: "6월",
    July: "7월",
    August: "8월",
    September: "9월",
    October: "10월",
    November: "11월",
    December: "12월",
    "": "",
  };

  return monthMap[month] || month;
};

/** 별자리를 한글로 변환하는 함수 */
export const convertSignToKorean = (sign: VillagerSign) => {
  const signMap: Record<VillagerSign, string> = {
    Aries: "양자리",
    Taurus: "황소자리",
    Gemini: "쌍둥이자리",
    Cancer: "게자리",
    Leo: "사자자리",
    Virgo: "처녀자리",
    Libra: "천칭자리",
    Scorpio: "전갈자리",
    Sagittarius: "사수자리",
    Capricorn: "염소자리",
    Aquarius: "물병자리",
    Pisces: "물고기자리",
  };

  return signMap[sign] || sign;
};

/** 첫 등장 게임을 한글로 변환하는 함수 */
export const convertDebutToKorean = (debut: VillagerDebut) => {
  const debutMap: Record<VillagerDebut, string> = {
    DNM: "동물의 숲",
    AC: "동물의 숲",
    E_PLUS: "동물의 숲 e+",
    NL: "튀어나와요 동물의 숲",
    CF: "타운으로 놀러가요 동물의 숲",
    WW: "놀러오세요 동물의 숲",
    "DNM+": "동물의 숲+",
    NH: "모여봐요 동물의 숲",
    NLWA: "튀어나와요 동물의 숲 amiibo+",
    HHD: "동물의 숲 해피 홈 디자이너",
    PC: "동물의 숲 포켓 캠프",
    WA: "튀어나와요 동물의 숲",
    FILM: "극장판 동물의 숲",
  };

  return debutMap[debut] || debut;
};

/** 주민 영문 이름을 한글 이름으로 변환하는 함수 */
export const convertVillagerNameToKorean = (name: VillagerName) => {
  const nameMap: Record<VillagerName, string> = {
    // A
    Ace: "페더",
    Admiral: "일섭",
    "Agent S": "2호",
    Agnes: "아그네스",
    Aisle: "아일",
    Al: "우락",
    Alfonso: "알베르트",
    Alice: "멜버른",
    Alli: "크로크",
    Amelia: "안데스",
    Anabelle: "아롱이",
    Analog: "아날로그",
    Anchovy: "안쵸비",
    Angus: "반데스",
    Anicotti: "라자냐",
    Ankha: "클레오",
    Annalisa: "설백",
    Annalise: "실부플레",
    Antonio: "퍼머거",
    Apollo: "아폴로",
    Apple: "애플",
    Astrid: "펑키맘",
    Audie: "모니카",
    Aurora: "오로라",
    Ava: "에바",
    Avery: "쿠스케처",
    Axel: "엑스엘리",
    Azalea: "페튜니아",
    Aziz: "아지즈",

    // B
    Baabara: "트로와",
    Bam: "록키",
    Bangle: "루주",
    Barold: "곰시",
    Bea: "베이글",
    Beardo: "베어드",
    Beau: "피터",
    Becky: "아리아",
    Bella: "이자벨",
    Belle: "벨",
    Benedict: "페니실린",
    Benjamin: "땡칠이",
    Bertha: "베티",
    Bessie: "베시",
    Bettina: "마르카",
    Betty: "베티",
    Bianca: "백희",
    Biff: "가브리엘",
    "Big Top": "3호",
    Bill: "코코아",
    Billy: "힘드러",
    Biskit: "로빈",
    Bitty: "비티",
    Blaire: "실루엣",
    Blanche: "신옥",
    Bluebear: "글루민",
    Bob: "히죽",
    Bonbon: "미미",
    Bones: "토미",
    Boomer: "팽기",
    Boone: "만복이",
    Boots: "풍작",
    Boris: "보리",
    Bow: "보우",
    Boyd: "보이드",
    Bree: "사라",
    Broccolo: "브로콜리",
    Broffina: "히킨",
    Bruce: "브루스",
    Bubbles: "차코",
    Buck: "바야시코프",
    Bud: "선글",
    Bunnie: "릴리안",
    Butch: "존",
    Buzz: "근엄",

    // C
    Cally: "파슬리",
    Camofrog: "충성",
    Canberra: "캔버라",
    Candi: "사탕",
    Carmen: "초코",
    Caroline: "캐롤라인",
    Carrie: "마미",
    Carrot: "캐럿",
    Cashmere: "캐시미어",
    Cece: "나기사",
    Celia: "티파니",
    Cephalobot: "기가",
    Cesar: "앨런",
    Chabwick: "펭구",
    Chadder: "치즈",
    Chai: "피카",
    Champ: "몽돌이",
    Charlise: "챠미",
    Chelsea: "첼시",
    Cheri: "아세로라",
    Cherry: "한나",
    Chester: "팬타",
    Chevre: "윤이",
    Chico: "치코",
    Chief: "대장",
    Chops: "돈후앙",
    Chow: "츄양",
    Chrissy: "크리스틴",
    Chuck: "척",
    Clara: "클라라",
    Claude: "비니거",
    Claudia: "신디",
    Clay: "햄둥",
    Cleo: "아이소토프",
    Clyde: "마철이",
    Coach: "철소",
    Cobb: "박사",
    Coco: "이요",
    Cole: "아마민",
    Colton: "안소니",
    Cookie: "베리",
    Cousteau: "왕서방",
    Cranston: "타키",
    Croque: "투투",
    Cube: "빙수",
    Cupcake: "컵케이크",
    Curlos: "카를로스",
    Curly: "햄까스",
    Curt: "뚝심",
    Cyd: "펑크스",
    Cyrano: "사지마",

    // D
    Daisy: "바닐라",
    Deena: "마리모",
    Deirdre: "나디아",
    Del: "파도맨",
    Deli: "델리",
    Derwin: "봉",
    Diana: "나탈리",
    Diva: "아이다",
    Dizzy: "휴지",
    Dobie: "켄",
    Doc: "토니",
    Dom: "차둘",
    Dora: "티미",
    Dotty: "서머",
    Dozer: "도저",
    Drago: "용남이",
    Drake: "푸아그라",
    Drift: "덕",

    // E
    Ed: "꺼벙",
    Egbert: "김희",
    Elina: "엘리나",
    Elise: "몽자",
    Ellie: "에끌레르",
    Elmer: "샤브렌",
    Eloise: "엘레핀",
    Elvis: "킹",
    Emerald: "에메랄드",
    Epona: "에포나",
    Erik: "자끄",
    Étoile: "에뜨와르",
    Eugene: "코알",
    Eunice: "곱슬이",

    // F
    Faith: "마치",
    Fang: "시베리아",
    Fauna: "솔미",
    Felicity: "예링",
    Felyne: "아이루",
    Filbert: "리키",
    Filly: "7호",
    Flash: "플래시",
    Flip: "원승",
    Flo: "레이라",
    Flora: "플라라",
    Flossie: "플로시",
    Flurry: "뽀야미",
    Francine: "프랑소와",
    Frank: "헐크",
    Freckles: "다랑어",
    Frett: "샹펜",
    Freya: "산드라",
    Friga: "사브리나",
    Frita: "웬디",
    Frobert: "구리구리",
    Fruity: "프루티",
    Fuchsia: "제시카",

    // G
    Gabi: "패티카",
    Gala: "꽃지",
    Ganon: "가논",
    Gaston: "대길",
    Gayle: "앨리",
    Gen: "겐",
    Genji: "토시",
    Gigi: "린다",
    Gladys: "빅토리아",
    Gloria: "마릴린",
    Goldie: "카라멜",
    Gonzo: "근성",
    Goose: "건태",
    Graham: "글라햄",
    Greta: "복자",
    Grizzly: "무뚝",
    Groucho: "거무틱",
    Gruff: "빌리",
    Gwen: "폴라",

    // H
    Hambo: "햄보",
    Hamlet: "햄스틴",
    Hamphrey: "햄쥐",
    Hank: "행크",
    Hans: "스나일",
    Harry: "올리버",
    Hazel: "아이리스",
    Hector: "헥터",
    Henry: "헨리",
    Hippeux: "데이빗",
    Holden: "홀든",
    Hopkins: "홉킨스",
    Hopper: "달만이",
    Hornsby: "뿌람",
    Huck: "스트로",
    Huggy: "허기",
    Hugh: "먹고파",

    // I
    Iggly: "김말이",
    Iggy: "이기",
    Ike: "대공",
    Inkwell: "멍무리",
    Ione: "스피카",

    // J
    Jacob: "야곱",
    Jacques: "쪼끼",
    Jambette: "에스메랄다",
    Jane: "제인",
    Jay: "참돌이",
    Jeremiah: "드리미",
    Jitters: "딩요",
    Joe: "조",
    Joey: "리처드",
    Jūbei: "주베이",
    Judy: "미애",
    Julia: "줄리아",
    Julian: "유니오",
    June: "메이",

    // K
    Kabuki: "가북희",
    Katt: "쵸이",
    Keaton: "프랭크",
    Ken: "오골",
    Ketchup: "케첩",
    Kevin: "멧지",
    "Kid Cat": "1호",
    Kidd: "염두리",
    Kiki: "캐비어",
    Kit: "키트",
    Kitt: "애플리케",
    Kitty: "쇼콜라",
    Klaus: "곰도로스",
    Knox: "금끼오",
    Kody: "아이다호",
    Koharu: "코하루",
    Kyle: "리카르도",

    // L
    Leigh: "리",
    Leonardo: "범호",
    Leopold: "티처",
    Lily: "레이니",
    Limberg: "단무지",
    Lionel: "라이오넬",
    Liz: "리즈",
    Lobo: "늑태",
    Lolly: "사이다",
    Lopez: "톰슨",
    Louie: "머슬",
    Lucha: "마스카라스",
    Lucky: "럭키",
    Lucy: "루시",
    Lulu: "룰루",
    Lyman: "오즈먼드",

    // M
    Mac: "챔프",
    "Madam Rosa": "마담 로사",
    Maddie: "마롱",
    Maelle: "앤",
    Maggie: "마가렛",
    Mallary: "스미모",
    Maple: "메이첼",
    Marcel: "에드워드",
    Marcie: "마리아",
    Marcy: "마르시",
    Margie: "샐리",
    Marina: "문리나",
    Marlo: "보스터",
    Marshal: "쭈니",
    Marty: "마티",
    Masa: "마사",
    Mathilda: "안젤라",
    Medli: "메들리",
    Megan: "캔디",
    Megumi: "메구미",
    Melba: "아델레이드",
    Meow: "미야옹",
    Merengue: "스트로베리",
    Merry: "유네찌",
    Midge: "핑글이",
    Mint: "민트",
    Mira: "미랑",
    Miranda: "미란다",
    Mitzi: "마르",
    Moe: "진상",
    Molly: "귀오미",
    Monique: "제인",
    Monty: "몽티",
    Moose: "핑",
    Mott: "릭",
    Muffy: "프릴",
    Murphy: "머피",

    // N
    Nan: "순이",
    Nana: "키키",
    Naomi: "화자",
    Nate: "박하스",
    Nibbles: "그리미",
    Nindori: "닌도리",
    Norma: "미자",
    Nosegay: "노즈게이",

    // O
    "O'Hare": "산토스",
    Octavian: "문복",
    Olaf: "안토니오",
    Olive: "올리브",
    Olivia: "올리비아",
    Opal: "오팔",
    Otis: "오티스",
    Oxford: "옥스포드",
    Ozzie: "동동이",

    // P
    Pancetti: "브리트니",
    Pango: "패트라",
    Paolo: "파올로",
    Papi: "마사마",
    Pashmina: "바바라",
    Pate: "나키",
    Patricia: "패트리샤",
    Patty: "밀크",
    Paula: "레이첼",
    Peaches: "말자",
    Peanut: "핑키",
    Pecan: "레베카",
    Peck: "문대",
    Peewee: "덤벨",
    Peggy: "체리",
    Pekoe: "재스민",
    Penelope: "찍순이",
    Penny: "페니",
    Petri: "리카",
    Petunia: "페튜니아",
    Phil: "케인",
    Phoebe: "휘니",
    Pierce: "세바스찬",
    Pierre: "피에르",
    Pietro: "피엘",
    Pigleg: "피그레그",
    Pinky: "링링",
    Piper: "파이프",
    Pippy: "로타",
    Plucky: "파타야",
    Poko: "포코",
    Pompom: "주디",
    Poncho: "봉추",
    Poppy: "다람",
    Portia: "블랜더",
    Prince: "카일",
    Puck: "하키",
    Puddles: "가위",
    Pudge: "우띠",
    Punchy: "빙티",
    Purrl: "타마",

    // Q
    Queenie: "택주",
    Quetzal: "케찰",
    Quillson: "덕근",
    Quinn: "시온",

    // R
    Raddle: "개군",
    Rasher: "글레이",
    Raymond: "잭슨",
    Renée: "뿔님이",
    Reneigh: "리아나",
    Rex: "렉스",
    Rhoda: "로다",
    Rhonda: "론다",
    Ribbot: "철컥",
    Ricky: "갈가리",
    Rilla: "릴라",
    Rio: "데자네",
    Rizzo: "조르쥐",
    Roald: "펭수",
    Robin: "파틱",
    Rocco: "곤잘레스",
    Rocket: "4호",
    Rod: "쟝",
    Rodeo: "로데오",
    Rodney: "지미",
    Rolf: "호랭이",
    Rollo: "롤로",
    Rooney: "마이크",
    Rory: "아더",
    Roscoe: "슈베르트",
    Rosie: "부케",
    Roswell: "삐로코",
    Rowan: "고메스",
    Ruby: "루나",
    Rudy: "찰스",

    // S
    Sally: "라라미",
    Samson: "피스",
    Sandy: "샌디",
    Sasha: "미첼",
    Savannah: "사반나",
    Scoot: "지키미",
    Shari: "젤리",
    Sheldon: "크리스",
    Shep: "밥",
    Sherb: "래미",
    Shinabiru: "시나비루",
    Shino: "요비",
    Shoukichi: "쇼키치",
    Simon: "시몬",
    Skye: "릴리",
    Sly: "하이드",
    Snake: "닌토",
    Snooty: "스누티",
    Soleil: "샨티",
    Sparro: "춘섭",
    Spike: "스쿼트",
    Spork: "포크",
    Sprinkle: "크리미",
    Sprocket: "헤르츠",
    Static: "스파크",
    Stella: "아크릴",
    Sterling: "은수리",
    Stinky: "땀띠",
    Stitches: "패치",
    Stu: "모리스",
    "Sue E": "수 E",
    Sunny: "써니",
    Sven: "스벤",
    Sydney: "시드니",
    Sylvana: "실바나",
    Sylvia: "실비아",

    // T
    "T-Bone": "티본",
    Tabby: "호냥이",
    Tad: "텀보",
    Tammi: "에이프릴",
    Tammy: "아네사",
    Tangy: "백프로",
    Tank: "탱크",
    Tarou: "타로",
    Tasha: "나타샤",
    Teddy: "병태",
    Tex: "볼트",
    Tia: "티나",
    Tiansheng: "제천",
    Tiara: "티아라",
    Tiffany: "바슬레",
    Timbra: "잔디",
    Tipper: "마틸다",
    Toby: "토비",
    Tom: "밴덤",
    Truffles: "탱고",
    Tucker: "맘모",
    Tutu: "연유",
    Twiggy: "핀틱",
    Twirp: "트워프",
    Tybalt: "티볼트",

    // U
    Ursala: "네이아",

    // V
    Valise: "발리즈",
    Velma: "벨마",
    Vesta: "메리어스",
    Vic: "노르망",
    Viché: "미사키",
    Victoria: "센트엘로",
    Violet: "줌마",
    Vivian: "바네사",
    Vladimir: "곰비",

    // W
    "W. Link": "울프 링크",
    Wade: "호떡",
    Walker: "벤",
    Walt: "관록",
    "Wart Jr.": "샘",
    Weber: "아잠만",
    Weldon: "웰던",
    Wendy: "눈송이",
    Whitney: "비앙카",
    Willow: "마리",
    Winnie: "카로틴",
    Wolfgang: "로보",
    Woolio: "울리오",

    // Y
    Yodel: "요델",
    Yuka: "유카리",

    // Z
    Zell: "넬슨",
    Zoe: "소면",
    Zucker: "탁호",
  };

  return nameMap[name];
};

/** 주민 명언을 한글로 변환하는 함수 */
export const convertQuoteToKorean = (quote: VillagerQuote) => {
  const quoteMap: Record<VillagerQuote, string> = {
    "": `자기소개가 없습니다.`,
    "If you love something, let it go. Then chase it down. What were you thinking?": `사랑하는 것이 있다면 놓아주어라. 그리고 쫓아가라. 뭘 생각하고 있었던 거야?`,
    "Only quitters give up.": `포기하는 자만이 포기한다.`,
    "You gotta put the pedal to the metal!": `액셀을 끝까지 밟아야 해!`,
    "You reap what you sow.": `뿌린 대로 거둔다.`,
    "Life is a buffet. Always go back for seconds.": `인생은 뷔페다. 항상 두 번째를 가져라.`,
    "Slow and steady wins the race.": `천천히 그리고 꾸준히 하는 자가 경주에서 이긴다.`,
    "Treat others as you would like to be treated.": `남을 대하듯이 자신을 대하라.`,
    "Think before you act.": `행동하기 전에 생각하라.`,
    "Pampering yourself is as important as food, water, and shelter!": `자신을 돌보는 것은 음식, 물, 피난처만큼 중요하다!`,
    "Dance like no one's watching!": `아무도 보지 않는 것처럼 춤춰라!`,
    "Why do today what you can put off until tomorrow?": `내일로 미룰 수 있는 일을 왜 오늘 하는가?`,
    "Even strong bulls cry.": `강한 황소도 운다.`,
    "The walls have ears.": `벽에도 귀가 있다.`,
    "All that glitters is not gold.": `반짝이는 모든 것이 금은 아니다.`,
    "Home is where the heart is.": `집은 마음이 있는 곳이다.`,
    "Let gossip go in one ear and out the other.": `소문은 한 귀로 듣고 한 귀로 흘려라.`,
    "Always go for the burn!": `항상 열정적으로 해라!`,
    "What goes up must come down.": `올라간 것은 반드시 내려온다.`,
    "One rotten apple spoils the barrel.": `썩은 사과 하나가 통째로 망친다.`,
    "The apple doesn't fall far from the tree.": `사과는 나무에서 멀리 떨어지지 않는다.`,
    "Be the kind of person your future self won't regret having been.": `미래의 자신이 후회하지 않을 사람이 되어라.`,
    "Always keep your cool.": `항상 냉정을 유지하라.`,
    "Early to bed, early to rise.": `일찍 자고 일찍 일어나라.`,
    "What goes around comes around.": `돌고 도는 것이 세상이다.`,
    "Do not compare a fly with an elephant.": `파리와 코끼리를 비교하지 마라.`,
    "Colorful petals, deep roots.": `화려한 꽃잎, 깊은 뿌리.`,
    "Don't just follow the flock.": `그냥 무리를 따르지 마라.`,
    "Get while the getting's good.": `기회가 있을 때 잡아라.`,
    "Don't blink or you'll miss it.": `눈 깜짝할 사이에 놓칠 수 있다.`,
    "Please DO feed the bears!": `곰들에게 먹이를 주세요!`,
    "The perfect pair complements each other.": `완벽한 한 쌍은 서로를 보완한다.`,
    "Fashion first!": `패션이 우선!`,
    "You snooze, you lose.": `잠들면 잃는다.`,
    "A fool and his Bells are soon parted.": `바보와 그의 벨은 곧 헤어진다.`,
    "A glamour shot is worth a thousand words.": `글래머 사진 한 장이 천 마디 말보다 낫다.`,
    "Don't put all your eggs in one basket.": `모든 달걀을 한 바구니에 담지 마라.`,
    "A good dog deserves a good treat.": `좋은 개는 좋은 간식을 받을 자격이 있다.`,
    "The best part of spring is the picnics!": `봄의 가장 좋은 부분은 피크닉이다!`,
    "No time like the present!": `지금만한 때는 없다!`,
    "There is such a thing as love at first sight.": `첫눈에 반하는 사랑이라는 것이 있다.`,
    "Eighth place is just the seventh loser.": `8등은 그냥 7번째 패자다.`,
    "A big nose never spoiled a handsome face.": `큰 코가 잘생긴 얼굴을 망친 적은 없다.`,
    "Even though there's no 'I' in team, there is a 'me'!": `팀에 '나'가 없어도 '나'는 있다!`,
    "Old dogs can learn new tricks.": `늙은 개도 새로운 기술을 배울 수 있다.`,
    "Let sleeping dogs lie.": `잠자는 개는 그냥 두어라.`,
    "Necessity is the mother of all invention.": `필요는 모든 발명의 어머니다.`,
    "Practice makes perfect.": `연습이 완벽을 만든다.`,
    "Nothing beats personal experience.": `개인적인 경험을 이길 수 있는 것은 없다.`,
    "Candy makes the world go 'round.": `사탕이 세상을 돌게 한다.`,
    "You only live once...or nine times.": `인생은 한 번뿐이다... 아니면 아홉 번.`,
    "Hindsight is always 20/20.": `뒤돌아보면 항상 명확하다.`,
    "A snack a day keeps the vacuum away.": `하루 한 간식이 청소기를 멀리한다.`,
    "Flying is believing.": `날아보는 것이 믿는 것이다.`,
    "Never settle for second best.": `절대 차선책에 만족하지 마라.`,
    "Strength lies in muscles.": `힘은 근육에 있다.`,
    "Life's short. Eat chocolate.": `인생은 짧다. 초콜릿을 먹어라.`,
    "There's always time to take a second look.": `다시 한 번 볼 시간은 항상 있다.`,
    "The gift says more about the giver.": `선물은 주는 사람에 대해 더 많이 말해준다.`,
    "One nap leads to another.": `한 번의 낮잠이 또 다른 낮잠으로 이어진다.`,
    "Don't peck the hand that feeds you.": `먹이를 주는 손을 쪼지 마라.`,
    "Nobody's perfect.": `완벽한 사람은 없다.`,
    "It's best to keep your lips and purse sealed.": `입과 지갑은 닫아두는 것이 최고다.`,
    "Keep your eyes on the prize.": `상을 향해 눈을 떼지 마라.`,
    "You're not living unless you're sweating!": `땀을 흘리지 않으면 살고 있는 게 아니다!`,
    "Hare today, gone tomorrow.": `오늘은 토끼, 내일은 사라진다.`,
    "A house without either a cat or a dog is a sad house indeed.": `고양이나 개가 없는 집은 정말 슬픈 집이다.`,
    "Pride'll put you in a pickle.": `자존심이 곤경에 빠뜨릴 것이다.`,
    "It's always teatime somewhere.": `어딘가에서는 항상 차 시간이다.`,
    "What you can't see can't hurt you.": `보이지 않는 것은 해칠 수 없다.`,
    "It's never too late to start over.": `다시 시작하기에 늦은 때는 없다.`,
    "The players may change, but the music stays the same.": `연주자는 바뀔 수 있지만 음악은 그대로다.`,
    "Absence makes the heart grow fonder.": `부재가 마음을 더 애틋하게 만든다.`,
    "New brooms sweep clean.": `새 빗자루가 깨끗하게 쓴다.`,
    "A mother's work is never done.": `어머니의 일은 끝이 없다.`,
    "100% Wool.": `100% 양모.`,
    "Too heads are better than one!": `머리 둘이 하나보다 낫다!`,
    "It's the thought that counts.": `마음이 중요하다.`,
    "Take me to your pizza.": `피자로 데려가 줘.`,
    "As soon as you can grow a mustache, do it.": `콧수염을 기를 수 있게 되면 바로 기워라.`,
    "Live, laugh, lasagna.": `살고, 웃고, 라자냐.`,
    "Meeting is just the start of us saying goodbye.": `만남은 작별 인사의 시작일 뿐이다.`,
    "He who chases two rabbits catches none.": `두 마리 토끼를 쫓는 자는 하나도 잡지 못한다.`,
    "You'll never get THIS monkey off your back!": `이 원숭이는 절대 등에서 내려오지 않을 거야!`,
    "Actions speak louder than words.": `행동이 말보다 크게 말한다.`,
    "Always look a gift horse in the mouth.": `선물받은 말의 입은 항상 들여다봐라.`,
    "Good things come in small packages.": `좋은 것은 작은 포장에 들어있다.`,
    "One dog barks at something, the rest bark at him.": `한 개가 무언가에 짖으면 나머지는 그에게 짖는다.`,
    "Sleep early. Wake late.": `일찍 자고 늦게 일어나라.`,
    "If you're gonna dream, dream big.": `꿈을 꾼다면 크게 꿔라.`,
    "Don't wish it were easier; wish you were better.": `더 쉬웠으면 하고 바라지 말고, 더 나아졌으면 하고 바라라.`,
    "You can't have your cake and eat it too.": `케이크를 가지면서 동시에 먹을 수는 없다.`,
    "All good things must come to an end.": `모든 좋은 것들은 끝이 있다.`,
    "A fool and their Bells are soon parted.": `바보와 그들의 벨은 곧 헤어진다.`,
    "Don't judge a rabbit by its ears.": `토끼를 귀로 판단하지 마라.`,
    "A tiger can't change its stripes.": `호랑이는 줄무늬를 바꿀 수 없다.`,
    "Life is just a bowl of cherries.": `인생은 그냥 체리 한 그릇이다.`,
    "There's something lovable in all of us.": `우리 모두에게는 사랑스러운 무언가가 있다.`,
    "The grass is always greener.": `잔디는 항상 더 푸르다.`,
    "Fool me once, shame on you. Fool me twice, shame on me.": `한 번 속이면 네 잘못, 두 번 속이면 내 잘못.`,
    "Might makes right.": `힘이 정의를 만든다.`,
    "Don't put off till tomorrow what you can do today.": `오늘 할 수 있는 일을 내일로 미루지 마라.`,
    "Little pitchers have big ears.": `작은 물주전자에 큰 귀가 있다.`,
    "Make hay while the sun shines.": `해가 비칠 때 건초를 만들어라.`,
    "Don't lose sight of what you're really after.": `정말로 추구하는 것을 놓치지 마라.`,
    "Jump first, ask questions later.": `먼저 뛰고 나중에 질문해라.`,
    "Hard work beats talent.": `노력이 재능을 이긴다.`,
    "Where there's smoke, there's fire.": `연기가 있는 곳에 불이 있다.`,
    "Sometimes you gotta learn to chill.": `때로는 진정하는 법을 배워야 한다.`,
    "If you want to know yourself better, ask your neighbors.": `자신을 더 잘 알고 싶다면 이웃에게 물어봐라.`,
    "Get fired up!": `열정을 불태워라!`,
    "A Bell saved is a Bell earned.": `절약한 벨이 번 벨이다.`,
    "Do what you want, but do it loud!": `하고 싶은 것을 해라, 하지만 크게 해라!`,
    "Don't punch your nose to spite your face.": `얼굴에 앙심을 품고 코를 치지 마라.`,
    "It's not always a dog-eat-dog world.": `항상 약육강식의 세상은 아니다.`,
    "Duck...duck...GOOSE!": `오리...오리...거위!`,
    "Legs of an antelope, heart of an eagle.": `영양의 다리, 독수리의 심장.`,
    "The hero is brave in deeds as well as words.": `영웅은 말뿐만 아니라 행동에서도 용감하다.`,
    "Righty tighty, lefty loosey.": `오른쪽으로 조이고, 왼쪽으로 풀고.`,
    "Everything in moderation. Except for snacks.": `모든 것을 적당히. 간식은 제외하고.`,
    "Sometimes you have to lose to win.": `때로는 이기기 위해 져야 한다.`,
    "Eyes are the windows to the soul.": `눈은 영혼의 창이다.`,
    "Keep it mellow.": `차분하게 유지해라.`,
    "Old longings never truly fade.": `오래된 그리움은 진정으로 사라지지 않는다.`,
    "One cannot live on carrots alone.": `당근만으로는 살 수 없다.`,
    "Be true to your most shiny self.": `가장 빛나는 자신에게 진실하라.`,
    "The squeaky wheel gets the cheese.": `삐걱거리는 바퀴가 치즈를 얻는다.`,
    "It's always a good hare day.": `항상 좋은 토끼의 날이다.`,
    "There is no room for two dragons in one pond.": `한 연못에 두 마리 용이 들어갈 자리는 없다.`,
    "...Quack.": `...꽥.`,
    "Always go for the gold!": `항상 금을 노려라!`,
    "Beauty is pretty!": `아름다움은 예쁘다!`,
    "You gotta break a few eggs to make an omelet.": `오믈렛을 만들려면 달걀 몇 개는 깨뜨려야 한다.`,
    "Do as I say, not as I do.": `내가 하는 대로 하지 말고 내가 말하는 대로 해라.`,
    "You need the sour to highlight the sweet.": `단맛을 돋보이게 하려면 신맛이 필요하다.`,
    "The horse doesn't pull the cart, the oats do.": `말이 수레를 끄는 게 아니라 귀리가 끈다.`,
    "An elephant never forgets.": "코끼리는 절대 잊지 않는다.",
    "Better a live coward than a forgotten hero.": `잊혀진 영웅보다는 살아있는 겁쟁이가 낫다.`,
    "Even the wildest horse can be tamed.": "가장 거친 말도 길들일 수 있다.",
    "If you're afraid of wolves, don't go to the woods.": `늑대가 무섭다면 숲에 가지 마라.`,
    "Who knows what the stars have in store for us?": `별들이 우리에게 무엇을 준비해 놓았는지 누가 알겠는가?`,
    "Imitation is the sincerest form of flattery.": `모방은 가장 진실한 형태의 아첨이다.`,
    "There is a point to every encounter.": `모든 만남에는 의미가 있다.`,
    "Never let your mind be what holds you back.": `마음이 발목을 잡게 하지 마라.`,
    "You mess with the wolf, you get the fangs.": `늑대를 건드리면 송곳니를 맞는다.`,
    "The first step is always the hardest.": `첫 번째 걸음이 항상 가장 어렵다.`,
    "Love has no bounds.": `사랑에는 경계가 없다.`,
    "Calmly gathering. Ah, the life of a hunter. ♪": `차분하게 모으기. 아, 사냥꾼의 삶이여. ♪`,
    "Don't go nuts or anything.": `미치거나 하지는 마라.`,
    "One horse against the world.": `세상에 맞선 한 마리 말.`,
    "See no donut, hear no donut, speak no donut.": `도넛을 보지도, 듣지도, 말하지도 마라.`,
    "Always keep a straight face.": `항상 무표정을 유지하라.`,
    "Pink is the new black.": `핑크가 새로운 블랙이다.`,
    "Squeak your mind, even if your voice shakes.": `목소리가 떨려도 마음을 표현하라.`,
    "You can't have wise folks if you don't have fools too.": `바보가 없으면 현명한 사람도 있을 수 없다.`,
    "Today is the last day of the rest of your life.": `오늘은 남은 인생의 마지막 날이다.`,
    "Act now before you change your mind!": `마음이 바뀌기 전에 지금 행동하라!`,
    "I'm in the prime of my life.": `나는 인생의 전성기에 있다.`,
    "Don't stray too far from the pack.": `무리에서 너무 멀리 벗어나지 마라.`,
    "You can't learn a life lesson from a fortune cookie.": `포춘 쿠키에서 인생 교훈을 배울 수는 없다.`,
    "Don't sweat the small potatoes.": `작은 감자에 대해 걱정하지 마라.`,
    "Always aim high!": `항상 높이 목표하라!`,
    "It takes one to know one.": `그런 사람이 그런 사람을 안다.`,
    "The more the merrier.": `많을수록 즐겁다.`,
    "Still waters run deep.": `고요한 물이 깊이 흐른다.`,
    "Never be ashamed to pig out.": `실컷 먹는 것을 부끄러워하지 마라.`,
    "An ear for an ear makes it hard to hear.": `귀에는 귀로 갚으면 듣기 어려워진다.`,
    "An ounce of prevention is worth a pound of cure.": `예방 1온스가 치료 1파운드의 가치가 있다.`,
    "Fall down seven times, get up eight.": `일곱 번 넘어져도 여덟 번 일어나라.`,
    "Look at the world through rose-colored glasses.": `장밋빛 안경으로 세상을 바라봐라.`,
    "Smiles are free.": `미소는 공짜다.`,
    "Time is money.": `시간은 돈이다.`,
    "A little bit of happiness is better than a lot of anguish.": `조금의 행복이 많은 고뇌보다 낫다.`,
    "Brothers are brothers, cheese is cheese.": `형제는 형제, 치즈는 치즈다.`,
    "Birds of a feather crow together.": `같은 깃털의 새들이 함께 운다.`,
    "Knowledge is power.": `지식은 힘이다.`,
    "The world is a stage.": `세상은 무대다.`,
    "Those who live in glass houses shouldn't throw stones.": `유리집에 사는 자는 돌을 던지지 말아야 한다.`,
    "Rocky road is more than just a flavor of ice cream.": `로키로드는 단순한 아이스크림 맛 이상이다.`,
    "Don't burn bridges.": `다리를 태우지 마라.`,
    "Mind your manners, or someone else will.": `예의를 지켜라, 아니면 다른 누군가가 지킬 것이다.`,
    "The ear's the thing.": `귀가 중요하다.`,
    "Children should be seen and not heard.": `아이들은 보이되 들리지 않아야 한다.`,
    "One good turn deserves another.": `좋은 일에는 좋은 일로 보답해야 한다.`,
    "Patience is a virtue for folks with time.": `인내는 시간이 있는 사람들의 미덕이다.`,
    "Never say never!": `절대 절대라고 말하지 마라!`,
    "The way to a frog's heart is through his stomach.": `개구리의 마음으로 가는 길은 위를 통해서다.`,
    "Mottoes are for the unoriginal.": `좌우명은 독창성이 없는 자들을 위한 것이다.`,
    "You can solve any problem if you just stick to it!": `끝까지 매달리면 어떤 문제든 해결할 수 있다!`,
    "A wise mammal gives danger a wide berth.": `현명한 포유동물은 위험을 멀리한다.`,
    "Always have a comeback.": `항상 반박할 말을 준비해라.`,
    "You can't hit a mosquito with a horseshoe.": `말굽으로 모기를 잡을 수는 없다.`,
    "Cold coffee makes for a cold demeanor.": `차가운 커피는 차가운 태도를 만든다.`,
    "Keep it real. Real chill.": `진실하게 살아라. 진짜 차분하게.`,
    "Six of one, half dozen of the other.": `이것도 저것도 마찬가지다.`,
    "The higher you climb, the smaller things look.": `높이 올라갈수록 사물이 작아 보인다.`,
    "A sucker is born every minute.": `매분마다 바보가 태어난다.`,
    "I was born under a lucky star.": `나는 행운의 별 아래 태어났다.`,
    "Your greatest strength can be your greatest weakness.": `가장 큰 장점이 가장 큰 약점이 될 수 있다.`,
    "Better to have loved and squawked than to have never loved at all.": `사랑하고 소리쳤던 것이 전혀 사랑하지 않았던 것보다 낫다.`,
    "It takes more muscles to frown than smile.": `찡그리는 것이 미소 짓는 것보다 더 많은 근육을 사용한다.`,
    "He who hesitates has lost.": `주저하는 자는 이미 진 것이다.`,
    "Sleep before you leap.": `뛰기 전에 잠을 자라.`,
    "When you're a team of one, you're always captain!": `혼자 팀이면 항상 주장이다!`,
    "Don't get your feathers all ruffled. Just chill.": `깃털을 곤두세우지 마라. 그냥 진정해.`,
    "I'm dancing my dreams away.": `꿈을 춤추며 보내고 있다.`,
    "Cut once, measure twice... Wait— reverse that.": `한 번 자르고 두 번 재라... 잠깐, 그 반대다.`,
    "Never trot when you can prance.": `뛸 수 있을 때 걷지 마라.`,
    "Dream big, expect little.": `크게 꿈꾸고 적게 기대하라.`,
    "If you make your opponent flinch, you have already won.": `상대방을 움찔하게 만들면 이미 이긴 것이다.`,
    "MeowMEOWmeow!": `야옹야옹야옹!`,
    "Even in a room full of fools, someone is the smartest.": `바보들로 가득한 방에서도 누군가는 가장 똑똑하다.`,
    "C'est la vie!": `그것이 인생이다!`,
    "When in doubt, eat a tomato!": `의심스러울 때는 토마토를 먹어라!`,
    "Sometimes it's OK to get dirty.": `때로는 더러워져도 괜찮다.`,
    "Crime doesn't pay!": `범죄는 돈이 되지 않는다!`,
    "Be yourself, everyone else is already taken.": `자신이 되어라, 다른 모든 사람은 이미 차지되었다.`,
    "Nothing ventured, nothing gained.": `모험하지 않으면 얻는 것도 없다.`,
    "Funny parents have funny kids.": `재미있는 부모에게는 재미있는 아이가 있다.`,
    "If you want something done well, do it yourself.": `잘하고 싶으면 직접 해라.`,
    "Pride goes before a fall.": `교만은 넘어짐의 앞잡이다.`,
    "A chicken's coop is its castle.": `닭의 우리는 그의 성이다.`,
    "The sky's the limit!": `하늘이 한계다!`,
    "Never trust a sheep in wolf's clothing.": `늑대 옷을 입은 양을 믿지 마라.`,
    "That's the way the energy bar crumbles.": `에너지 바가 부서지는 방식이 그렇다.`,
    "The bigger the fish, the bigger your dinner.": `물고기가 클수록 저녁도 크다.`,
    "Don't jump to conclusions!": `성급한 결론을 내리지 마라!`,
    "Don't build a better mousetrap.": `더 나은 쥐덫을 만들지 마라.`,
    "Love is blind.": `사랑은 맹목적이다.`,
    "If it's not one thing, it's another.": `이것이 아니면 저것이다.`,
    "Laughter is the best medicine.": `웃음이 최고의 약이다.`,
    "Always look both ways before crossing the street.": `길을 건널 때는 항상 양쪽을 봐라.`,
    "It's all about the muscle.": `모든 것은 근육에 관한 것이다.`,
    "Birds of a feather, et cetera, et cetera...": `같은 깃털의 새들, 기타 등등...`,
    "Don't bite the hand that feeds you.": `먹이를 주는 손을 물지 마라.`,
    "The best is yet to come.": `최고는 아직 오지 않았다.`,
    "Eucalyptus is the spice of life.": `유칼립투스는 인생의 향신료다.`,
    "Sometimes life is rough.": `때로는 인생이 거칠다.`,
    "The IT revolution is under way.": `IT 혁명이 진행 중이다.`,
    "A wise duck takes care of its bill.": `현명한 오리는 자신의 부리를 돌본다.`,
    "All a plant needs is love...and sun and water and soil.": `식물에게 필요한 것은 사랑... 그리고 햇빛과 물과 흙이다.`,
    "Purple is the color of royalty.": `보라색은 왕족의 색이다.`,
    "Waste not, want not.": `낭비하지 않으면 부족하지 않다.`,
    "There's not a dog so bad that he won't wag his tail.": `꼬리를 흔들지 않을 정도로 나쁜 개는 없다.`,
    "The road to a friend's house is never long.": `친구 집으로 가는 길은 결코 길지 않다.`,
    "Keep your feet on the ground.": `발을 땅에 붙이고 있어라.`,
    "If you can't say something nice, don't say anything at all.": `좋은 말을 할 수 없다면 아무 말도 하지 마라.`,
    "You gotta walk the walk if you're gonna talk the talk.": `말을 하려면 행동도 해야 한다.`,
    "Seize the day.": `오늘을 잡아라.`,
    "Just wait until I get started!": `내가 시작할 때까지만 기다려!`,
    "Nail polish is thicker than water.": `매니큐어가 물보다 진하다.`,
    "A bird on the wing is worth two on the ground.": `날고 있는 새 한 마리가 땅에 있는 두 마리보다 낫다.`,
    "Take a page out of someone else's book, if it's a good book.": `좋은 책이라면 다른 사람의 책에서 한 페이지를 가져와라.`,
    "A friend who shares is a friend who cares.": `나누는 친구가 배려하는 친구다.`,
    "Life is a piece of cake.": `인생은 케이크 한 조각이다.`,
    "A smile increases your face value.": `미소는 얼굴 가치를 높인다.`,
    "When the world gets cold, just fly south.": `세상이 추워지면 남쪽으로 날아가라.`,
    "Always lead by example.": `항상 모범을 보여라.`,
    "Always help a friend in need.": `곤경에 처한 친구를 항상 도와라.`,
    "If the world is flooded, it will be easy for the duck.": `세상이 물에 잠기면 오리에게는 쉬울 것이다.`,
    "Practice makes purrrfect!": `연습이 완벽을 만든다냥!`,
    "Ignorance is bliss.": `무지는 축복이다.`,
    "Like water off a duck's back.": `오리 등에서 물이 흘러내리듯.`,
    "All publicity is good publicity!": `모든 홍보는 좋은 홍보다!`,
    "No news is good news.": `소식이 없는 것이 좋은 소식이다.`,
    "A cornered rat will summon the courage to bite a cat.": `궁지에 몰린 쥐는 고양이를 물 용기를 낸다.`,
    "The lion's share goes to the lion.": `사자의 몫은 사자에게 간다.`,
    "There's a black sheep in every family.": `모든 가족에는 말썽꾸러기가 있다.`,
    "More money, more problems.": `돈이 많으면 문제도 많다.`,
    "Nanny-nanny boo-boo!": `놀리기 놀리기!`,
    "Bread always falls peanut-butter side down.": `빵은 항상 땅콩버터 면이 아래로 떨어진다.`,
    "Moo like there's no tomorrow.": `내일이 없는 것처럼 음매하라.`,
    "Be true to yourself.": `자신에게 진실하라.`,
    "Appearances are, like, totally deceiving.": `외모는 완전히 속이는 것이다.`,
    "If you want what you have, then you'll have what you want.": `가진 것을 원한다면 원하는 것을 갖게 될 것이다.`,
    "It's not old; it's vintage.": `오래된 게 아니라 빈티지다.`,
    "Don't be a sucker!": `바보가 되지 마라!`,
    "Keep your nose clean.": `코를 깨끗하게 유지하라.`,
    "Sticky fingers attract bees.": `끈적한 손가락은 벌을 끌어들인다.`,
    "There's an exception to every rule.": `모든 규칙에는 예외가 있다.`,
    "However little you think of an elephant, you can't say it won't fill a pot.": `코끼리를 아무리 작게 생각해도 냄비를 채우지 못한다고 할 수는 없다.`,
    "Half a loaf is better than none.": `반 덩어리라도 없는 것보다 낫다.`,
    "Always get it in writing.": `항상 서면으로 받아라.`,
    "A thing of beauty is a joy forever.": `아름다운 것은 영원한 기쁨이다.`,
    "When it works, it works.": `될 때는 된다.`,
    "Never say neigh.": `절대 네이라고 말하지 마라.`,
    "Before you judge someone, walk a mile in their hooves.": `누군가를 판단하기 전에 그들의 발굽으로 1마일을 걸어봐라.`,
    "A duck won't bite you.": `오리는 물지 않는다.`,
    "A friend in need is a friend indeed!": `곤경에 처한 친구가 진정한 친구다!`,
    "Trends always make a comeback.": `유행은 항상 돌아온다.`,
    "Every day is a gift.": `매일이 선물이다.`,
    "Never take a nibble when you can take a bite.": `한 입 베어 물 수 있을 때 조금씩 먹지 마라.`,
    "Promises are like pie crusts— they're made to be broken.": `약속은 파이 껍질과 같다 - 깨뜨리기 위해 만들어진다.`,
    "The best defense is a good offense.": `최고의 방어는 좋은 공격이다.`,
    "Look behind you.": `뒤를 봐라.`,
    "We're all diamonds in the rough.": `우리는 모두 원석 속의 다이아몬드다.`,
    "Let bygones be bygones.": `지나간 일은 지나간 일로 두어라.`,
    "One mile or a thousand makes no difference to love.": `1마일이든 천 마일이든 사랑에는 차이가 없다.`,
    "Our DNA is only the beginning of the story.": `우리의 DNA는 이야기의 시작일 뿐이다.`,
    "Best not to say too much.": `너무 많이 말하지 않는 것이 좋다.`,
    "You can't keep a good bird down.": `좋은 새는 억누를 수 없다.`,
    "When someone says fly, you ask how high!": `누군가 날라고 하면 얼마나 높이 날지 물어봐라!`,
    "Be the class clown.": `반의 광대가 되어라.`,
    "Time spent with friends is time well spent.": `친구와 보낸 시간은 잘 보낸 시간이다.`,
    "Where there's life, there's hope.": `생명이 있는 곳에 희망이 있다.`,
    "Fake it till you make it.": `성공할 때까지 가짜로라도 해라.`,
    "Keep your crumbs out of the bed.": `침대에 부스러기를 떨어뜨리지 마라.`,
    "Happiness is a rainy day!": `행복은 비 오는 날이다!`,
    "Fortune favors the brave!": `행운은 용감한 자를 돕는다!`,
    "It's all about positive thinking!": `모든 것은 긍정적인 생각에 달려있다!`,
    "Charity begins at home.": `자선은 집에서 시작된다.`,
    "Catch more flies with honey than vinegar.": `식초보다 꿀로 더 많은 파리를 잡는다.`,
    "A bad attitude will land you in the penalty box.": `나쁜 태도는 페널티 박스에 들어가게 한다.`,
    "Look before you leap.": `뛰기 전에 봐라.`,
    "There's no such thing as a free lunch.": `공짜 점심은 없다.`,
    "There's always more fish in the sea!": `바다에는 항상 더 많은 물고기가 있다!`,
    "Let them drink cream.": `그들이 크림을 마시게 하라.`,
    "You never get a second chance to make a first impression.": `첫인상을 만들 두 번째 기회는 없다.`,
    "There is beauty in everything.": `모든 것에는 아름다움이 있다.`,
    "Step on a violet, and you'll smell forgiveness.": `제비꽃을 밟으면 용서의 향기를 맡을 것이다.`,
    "A healthy mind makes for a healthy body.": `건강한 마음이 건강한 몸을 만든다.`,
    "Don't judge a book by its cover.": `겉표지로 책을 판단하지 마라.`,
    "Stay on brand!": `브랜드를 유지하라!`,
    "Reckless youth makes rueful age.": `무모한 젊음이 후회하는 노년을 만든다.`,
    "You can only be you, so be the best you that you can be.": `너는 너일 수밖에 없으니 최고의 너가 되어라.`,
    "Three wrongs don't make a right, but three rights make a left.": `세 번의 잘못이 옳음을 만들지는 않지만, 세 번의 우회전은 좌회전을 만든다.`,
    "Don't look down your nose at people!": `사람들을 깔보지 마라!`,
    "Never rest, never rust.": `쉬지 않으면 녹슬지 않는다.`,
    "You gotta break a few shells to get to the nut.": `견과류를 얻으려면 껍질 몇 개는 깨뜨려야 한다.`,
    "When there's a will, there's a way.": `의지가 있는 곳에 길이 있다.`,
    "Self-care? Best care.": `자기 관리? 최고의 관리.`,
    "Evil lurks everywhere.": `악은 어디에나 숨어있다.`,
    "You must learn to waddle before you can swim.": `수영하기 전에 뒤뚱거리는 법을 배워야 한다.`,
    "Always keep your wings manicured so you can fly away.": `날아갈 수 있도록 항상 날개를 다듬어 놓아라.`,
    "The only thing to fear is fear itself... and wasps!": `두려워할 것은 두려움 자체뿐... 그리고 말벌!`,
    "Art feeds the soul. So does pizza.": `예술은 영혼을 먹여 살린다. 피자도 마찬가지다.`,
    "If you can't beat 'em, work harder.": `이길 수 없다면 더 열심히 일해라.`,
    "Zzzzzzzzzzzzzzzzz...": `쿨쿨쿨쿨쿨...`,
    "Everything is temporary.": `모든 것은 일시적이다.`,
    "Don't skip lunch. Ever.": `점심은 절대 거르지 마라.`,
    "Bob and weave! Bob and weave!": `피하고 엮어라! 피하고 엮어라!`,
    "Set 'em up and knock 'em down.": `세워놓고 쓰러뜨려라.`,
    "Trouble rides a fast horse.": `문제는 빠른 말을 탄다.`,
    "One good purr deserves another.": `좋은 골골거림에는 또 다른 골골거림이 어울린다.`,
    "Keep your eyes on the skies.": `하늘을 주시하라.`,
    "Refuse to lose.": `지는 것을 거부하라.`,
    "You can always take the red-eye.": `항상 야간 비행기를 탈 수 있다.`,
    "Always land on your feet!": `항상 발로 착지하라!`,
    "Even the smallest acorn may grow into the tallest tree.": `가장 작은 도토리도 가장 큰 나무로 자랄 수 있다.`,
    "Squeak softly and carry a big stick.": `조용히 찍찍거리고 큰 막대기를 들고 다녀라.`,
    "Soaring through the sky takes more than a pair of wings.": `하늘을 날아오르는 것은 날개 한 쌍 이상이 필요하다.`,
    "Timing is everything.": `타이밍이 전부다.`,
    "Keep your chin up!": `턱을 들어라!`,
    "Some birds avoid the water, ducks look for it.": `어떤 새들은 물을 피하지만 오리는 물을 찾는다.`,
    "A good start leads to a good end.": `좋은 시작이 좋은 끝으로 이어진다.`,
    "Winners don't quit, and quitters never win.": `승자는 포기하지 않고, 포기하는 자는 절대 이기지 못한다.`,
    "Even dogs won't get in the middle of true love.": `진정한 사랑에는 개도 끼어들지 않는다.`,
    "Forty winks is never enough.": `40번의 눈 깜빡임으로는 충분하지 않다.`,
    "Better the demon you know than the one you do not.": `모르는 악마보다 아는 악마가 낫다.`,
    "Friends go together like peanut butter and bananas.": `친구들은 땅콩버터와 바나나처럼 잘 어울린다.`,
    "Love makes the world go 'round.": `사랑이 세상을 돌게 한다.`,
    "Don't bite off more than you can chew.": `씹을 수 있는 것보다 많이 물지 마라.`,
    "A good ninja is neither seen nor heard.": `좋은 닌자는 보이지도 들리지도 않는다.`,
    "Request forgiveness, not permission.": `허락이 아닌 용서를 구하라.`,
    "Sometimes dreams are merely dreams.": `때로는 꿈은 그저 꿈일 뿐이다.`,
    "The proof of the pudding is in the eating.": `푸딩의 증명은 먹어보는 것에 있다.`,
    "Keep your eye on the ball.": `공에서 눈을 떼지 마라.`,
    "It's never too late for a snack.": `간식을 먹기에 늦은 때는 없다.`,
    "Frosting is just the icing on the cake.": `프로스팅은 케이크 위의 아이싱일 뿐이다.`,
    "Strike while the iron is hot.": `쇠가 뜨거울 때 쳐라.`,
    "Lightning never strikes twice.": `번개는 두 번 치지 않는다.`,
    "100% Natural Fiber.": `100% 천연 섬유.`,
    "Discretion is the better part of valor.": `신중함이 용기의 더 나은 부분이다.`,
    "If the mask fits, wear it!": `가면이 맞으면 써라!`,
    "A stitch in time saves nine.": `때맞춘 한 바늘이 아홉 바늘을 절약한다.`,
    "As a cow grows, so do its nostrils.": `소가 자라면 콧구멍도 자란다.`,
    "Sail wherever the wind takes you.": `바람이 데려가는 곳으로 항해하라.`,
    "Remember to see the forest between the trees.": `나무들 사이의 숲을 보는 것을 기억하라.`,
    "Hop first; ask questions later.": `먼저 뛰고 나중에 질문하라.`,
    "Don't have a cow.": `소를 키우지 마라.`,
    "You can never have too much of a good thing!": `좋은 것은 아무리 많아도 지나치지 않다!`,
    "Take a leap!": `도약하라!`,
    "Always be down to monkey around!": `항상 장난칠 준비를 하고 있어라!`,
    "If a job is worth doing, do it right!": `할 가치가 있는 일이라면 제대로 해라!`,
    "When life gives you lemons, make lemonade!": `인생이 레몬을 주면 레모네이드를 만들어라!`,
    "Remember to keep your core muscles engaged!": `코어 근육을 계속 사용하는 것을 기억하라!`,
    "There's no such thing as a safe secret.": `안전한 비밀이란 없다.`,
    "No pain, no gain!": `고통 없이는 얻는 것도 없다!`,
    "Rules were made to be broken.": `규칙은 깨뜨리기 위해 만들어졌다.`,
    "Tea is a cup of life.": `차는 인생의 한 잔이다.`,
    "The world is more swole than you will ever fully know.": `세상은 당신이 완전히 알 수 있는 것보다 더 근육질이다.`,
    "What is cheap is most costly.": `싼 것이 가장 비싸다.`,
    "Don't pine for the past.": `과거를 그리워하지 마라.`,
    "It takes two to tango.": `탱고는 둘이 춰야 한다.`,
    "Toby or not Toby? I don't know, I'm asking you.": `토비냐 토비가 아니냐? 모르겠어, 너에게 묻는 거야.`,
    "There's no use crying over spilled milk.": `엎질러진 우유를 두고 울어봤자 소용없다.`,
    "The best things in life are free.": `인생에서 가장 좋은 것들은 공짜다.`,
    "Time makes fossils of us all.": `시간은 우리 모두를 화석으로 만든다.`,
    "Even the best of friends start out as strangers.": `가장 좋은 친구들도 처음에는 낯선 사람이었다.`,
    "It's the early bird that catches the worm!": `일찍 일어나는 새가 벌레를 잡는다!`,
    "There's no excuse for half-baked potatoes.": `덜 익은 감자에 대한 변명은 없다.`,
    "Surround yourself with things you love.": `사랑하는 것들로 자신을 둘러싸라.`,
    "Work smarter, not harder.": `더 열심히가 아니라 더 똑똑하게 일하라.`,
    "No sweater off my back.": `내 등의 스웨터는 아니다.`,
    "You mess with the bull, you get the horns.": `황소를 건드리면 뿔을 맞는다.`,
    "TWO heads are better than one!": `머리 둘이 하나보다 낫다!`,
    "Don't put the cart before the horse.": `말 앞에 수레를 두지 마라.`,
    "Pearls are a pink gorilla's best friend.": `진주는 분홍 고릴라의 가장 친한 친구다.`,
    "Onwards and upwards!": `앞으로 그리고 위로!`,
    "Trouble never comes alone.": `문제는 혼자 오지 않는다.`,
    "Walk on the wild side.": `야생의 편에서 걸어라.`,
    "Which came first, the seeds or the sunflower?": `씨앗이 먼저인가, 해바라기가 먼저인가?`,
    "The dog wags his tail, not for you, but for your bread.": `개는 당신을 위해서가 아니라 당신의 빵을 위해 꼬리를 흔든다.`,
    "Take the good with the bad.": `좋은 것과 나쁜 것을 함께 받아들여라.`,
    "Age before beauty.": `미모보다 나이가 먼저.`,
    "Today's adults are yesterday's children.": `오늘의 어른들은 어제의 아이들이다.`,
    "Every cloud has a silver lining.": `모든 구름에는 은빛 테두리가 있다.`,
    "Don't cry wolf unless you mean it.": `진심이 아니라면 늑대가 온다고 외치지 마라.`,
    "You can't fight your genes.": `유전자와 싸울 수는 없다.`,
    "Smile, and the world smiles with you.": `미소 지으면 세상도 함께 미소 짓는다.`,
    "Don't be afraid to show your fangs.": `송곳니를 드러내는 것을 두려워하지 마라.`,
    "Beauty is in the eye of the beholder.": `아름다움은 보는 이의 눈에 있다.`,
    "Clothes totally make the mammal.": `옷이 포유동물을 완전히 만든다.`,
    "Don't sign until you've read the whole thing.": `전체를 읽기 전까지는 서명하지 마라.`,
    "There's no such thing as luck.": `운이라는 것은 없다.`,
  };

  return quoteMap[quote] || quote;
};
